git:
  submodules: false
before_install:
  - git submodule update --init --recursive

language: python
python: "3.6"

install:
  - make install

script:
  - make test

before_deploy:
  - git tag "$(make tag-minor)"

deploy:
  - provider: pypi
    user: ${PYPI_USER}
    password: ${PYPI_PASSWORD}
    skip_cleanup: true
    distributions: "sdist bdist_wheel"
    on:
      branch: master
      tags: false

notifications:
  webhooks:
    urls:
      - "$WEBHOOKS_URL"
    on_success: change 
    on_failure: always  
    on_start: change 
    on_cancel: always 
    on_error: always
    
