language: python
python: "3.6"

script:
  - pip3 install .
  - python3 setup.py test

notifications:
  webhooks:
    urls:
      - "$WEBHOOKS_URL"
    on_success: change 
    on_failure: always  
    on_start: change 
    on_cancel: always 
    on_error: always
    
