language: python
python: "3.6"

install:
  - make venv
  - source venv/bin/activate
  - make install

script:
  - make test

deploy:
  provider: pypi
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
  on:
    branch: master
    tags: true

notifications:
  webhooks:
    urls:
      - "$WEBHOOKS_URL"
    on_success: change 
    on_failure: always  
    on_start: change 
    on_cancel: always 
    on_error: always
    
